# Clé unique du projet que vous avez créé dans SonarQube
sonar.projectKey=pfe-frontend

# Nom qui sera affiché dans l'interface de SonarQube
sonar.projectName=PFE Frontend

# Indique où se trouvent les fichiers de code source (ici, le dossier 'src')
sonar.sources=src

# Exclut les dossiers qui ne doivent pas être analysés
sonar.exclusions=**/node_modules/**